services:
  web:
    build: .
    container_name: aireader_web
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app/static/uploads:/app/app/static/uploads
      - ./app/static/audios:/app/app/static/audios
      - sqlite_data:/app/instance
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - init_db
    networks:
      - aireader_network

  init_db:
    build: .
    container_name: aireader_init_db
    command: >
      python -c "
      from app import app; 
      from app.models.db import db; 
      from app.models.user import User; 
      from app.models.pdf import PDF, AudioFile; 
      app.app_context().push(); 
      db.create_all(); 
      print('Banco de dados inicializado com sucesso!')
      "
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - sqlite_data:/app/instance
    networks:
      - aireader_network

networks:
  aireader_network:
    driver: bridge

volumes:
  sqlite_data: 